import {
  homeRoute,
  indexRoute,
  loginAPIRoute,
  loginRoute,
  loginRouteWithNext,
  logoutAPIRoute,
  logoutRoute,
  magicLoginRoute,
  onboardingAPIRoute,
  onboardingRoute,
  resetAPIRoute,
  resetRoute,
  sessionAPIRoute,
  signupAPIRoute,
  signupRoute,
  termsRoute,
} from './utils';
export {
  homeRoute,
  indexRoute,
  loginAPIRoute,
  loginRoute,
  loginRouteWithNext,
  logoutAPIRoute,
  logoutRoute,
  magicLoginRoute,
  onboardingAPIRoute,
  onboardingRoute,
  resetAPIRoute,
  resetRoute,
  sessionAPIRoute,
  signupAPIRoute,
  signupRoute,
  termsRoute,
};
